### ISSUE TITLE
Interested in translating the subtitles by hand

### ISSUE THREAD

**Issue by ManlyMarco** [Rieght/IOSubtitles#2]
Hello! Do you still have the Japanese script, and if so how good is it? If the quality was decent enough I could have it manually translated. We can talk on discord (manlymarco) or f95 (ManlyMarco) if you'd like.

**Comment by Rieght** [comment]
Hi, I transcripted the game with whisper ai and the quality varies. The english script had issues at later corruption levels, where the characters start to speak less clearly. I don't know how much that applies to the transcript. Better evaluate that for yourself. 
Additionally, whisper sometimes adds random words/letters into the script and adds random phrases when the file has no dialogue in it. (like 'thank you for watching!') 
If there are further questions DM me on discord (rieght).
[subtitles_jp.zip](https://github.com/Rieght/IOSubtitles/files/12642333/subtitles_jp.zip)

**Comment by ManlyMarco** [comment]
Yeah, it looks like the person translating would need to listen to the voice clips anyways, in that case it's sadly not viable I think. Thank you for the reply though!

Could this subs file be used with the plugin to add Japanese subtitles? It's not going to be a very commonly used feature, but if it's basically free then it could help someone, somewhere.

**Comment by ManlyMarco** [comment]
Given that #3 is merged I guess it's time to close this issue, cheers.
